const fs = require('fs');
var minify = require('html-minifier').minify;

const dev = process.argv[2] === 'dev';

const baseDir = './src/html/';
var destDir = './dist/';
if (dev) {
	destDir = './dev/';
}

const entry = [
	'404.html',
	'account.html',
	'bangumi.html',
	'confirm_email.html',
	'confirm_special_register.html',
	'console.html',
	'image.html',
	'index.html',
	'info.html',
	'login.html',
	'message.html',
	'new_email.html',
	'password_reset.html',
	'policy.html',
	'register.html',
	'request_password_reset.html',
	'special_register.html',
];

for (var i = 0; i < entry.length; i++) {
	let filename = entry[i];
	fs.readFile(baseDir + filename, 'utf8', (err, data) => {
		if (err) {
			console.error(err);
			return;
		}
		let result = minify(data, {
			includeAutoGeneratedTags: true,
			removeAttributeQuotes: true,
			removeComments: true,
			removeRedundantAttributes: true,
			sortAttributes: true,
			sortClassName: true,
			useShortDoctype: true,
			collapseWhitespace: true
		});
		if (dev) {
			result = result.replaceAll('href=/', 'href=');
			result = result.replaceAll('src=/', 'src=');
		}
		fs.writeFile(destDir + filename, result, err => {
			if (err) {
				console.error(err);
			}
			console.log('Successfully written ' + destDir + filename);
		});
	});
}